# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
  resourceGroup:
    type: string
    metadata:
      description: Name of the existing resource group

variables:
 resourceGroupName: "[parameters(resourceGroup)]"


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'ARM-SC'
    #subscriptionName: ''
    action: 'Create Or Update Resource Group'
    resourceGroupName: "[variables('resourceGroupName')]"
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: vNetdeploy.json
    csmParametersFile: vNet.parameter.json
    deploymentMode: 'Incremental'



