# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: resourceGroup # name of the parameter; required
  type: string # data type of the parameter; required
  default: false


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: 'ARM-SC'
    #subscriptionName: ''
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: vNetdeploy.json
    csmParametersFile: vNet.parameter.json
    deploymentMode: 'Incremental'



