# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
#- master

pool:
  vmImage: 'ubuntu-latest'

parameters:
- name: resourceGroup # name of the parameter; required
  type: string # data type of the parameter; required
  default: aks-resg-001
- name: serviceConnectionName
  type: string
  default: ARM-SC


steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    ConnectedServiceName: ${{ parameters.serviceConnectionName }}
    action: 'Create Or Update Resource Group'
    resourceGroupName: ${{ parameters.resourceGroup }}
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: aks-cluster/azuredeploy.json
    csmParametersFile: aks-cluster/azuredeploy.parameter.json
    deploymentMode: 'Incremental'



